# Generated by Django 4.1.2 on 2022-10-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0002_author_remove_movie_name_movie_title_movie_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='summary',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
